version: '2.1'
services:

  # PG instance
  crud-postgres:
    container_name: crud-postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: testdb
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      PGDATA: /tmp
    stop_grace_period: 5s
    stdin_open: true
    ports:
      - "5410:5432"
    expose:
      - "5432"
    volumes: # Ссылается на область с базой
      - ./db/postgre:/var/lib/postgresql/data

    # nginx
  crud-nginx:
    #image: nginx:latest
    build: ./Docker/nginx
    stdin_open: true
    stop_grace_period: 1s
    links:
      - crud-php-fpm:php
    ports:
      - "1010:1000"
    expose:
      - "1000"
    volumes: # Передает кофигурацию для веб-сервера
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    #volumes_from:
    #  - test-code
      - ./:/var/www

  # PHP-FPM
  crud-php-fpm:
    container_name: crud-php-fpm
    # image: phpdockerio/php73-fpm
    build: ./Docker/php_fpm
    environment:
      APP_DEBUG: "true"
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: testdb
      DB_USERNAME: postgres
      DB_PASSWORD: password
    stdin_open: true
    stop_grace_period: 3s
    links:
      - crud-postgres:db
    #volumes_from:
    #  - test-code
    volumes:
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./:/var/www

  # Code
  #test-code:
  #  image: busybox
  #  user: www-data
  #  stdin_open: true
  #  volumes:
   #   - ./:/var/www
